--------------------------------------------------------
--  File created - Wednesday-January-06-2021   
--------------------------------------------------------
DROP TABLE "AYMEN"."CARTEFIDELITE";
DROP TABLE "AYMEN"."CLIENTS";
DROP TABLE "AYMEN"."COLIS";
DROP TABLE "AYMEN"."COMMANDE";
DROP TABLE "AYMEN"."COMMANDE_COLIS";
DROP TABLE "AYMEN"."CONGE";
DROP TABLE "AYMEN"."EMPLOYE";
DROP TABLE "AYMEN"."ENTREPOTS";
DROP TABLE "AYMEN"."USERS";
DROP TABLE "AYMEN"."VEHICULE";
--------------------------------------------------------
--  DDL for Table CARTEFIDELITE
--------------------------------------------------------

  CREATE TABLE "AYMEN"."CARTEFIDELITE" 
   (	"NUMERO" NUMBER, 
	"POINTS" NUMBER, 
	"CHEQUE" NUMBER, 
	"DATE_EM" DATE, 
	"DATE_EX" DATE, 
	"REFER_CLIENTS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "AYMEN"."CLIENTS" 
   (	"REF_C" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"NOM_C" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"PAYS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COLIS
--------------------------------------------------------

  CREATE TABLE "AYMEN"."COLIS" 
   (	"HAUTEUR" FLOAT(126), 
	"LARGEUR" FLOAT(126), 
	"LONGEUR" FLOAT(126), 
	"CODE_BARE" NUMBER, 
	"POIDS" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "AYMEN"."COMMANDE" 
   (	"NUMERO" NUMBER, 
	"DESCRIPTION" VARCHAR2(150 BYTE), 
	"DATEDECOMMANDE" DATE, 
	"MODEDEPAIMENT" VARCHAR2(20 BYTE), 
	"MONTANT" FLOAT(126), 
	"ID_EMP" NUMBER, 
	"REF_CLIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE_COLIS
--------------------------------------------------------

  CREATE TABLE "AYMEN"."COMMANDE_COLIS" 
   (	"NUMERO_C" NUMBER, 
	"ETAT" VARCHAR2(20 BYTE), 
	"CODE_COLIS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONGE
--------------------------------------------------------

  CREATE TABLE "AYMEN"."CONGE" 
   (	"IDC" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DEB" DATE, 
	"FIN" DATE, 
	"DUREE" NUMBER, 
	"ETAT" VARCHAR2(20 BYTE), 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "AYMEN"."EMPLOYE" 
   (	"IDEMP" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATEN" DATE, 
	"NUMTEL" VARCHAR2(20 BYTE), 
	"ADR" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENTREPOTS
--------------------------------------------------------

  CREATE TABLE "AYMEN"."ENTREPOTS" 
   (	"REF" NUMBER, 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"REGION" VARCHAR2(20 BYTE), 
	"NSALLES" VARCHAR2(20 BYTE), 
	"NVEHICULES" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "AYMEN"."USERS" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULE
--------------------------------------------------------

  CREATE TABLE "AYMEN"."VEHICULE" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"NUMDECHASSIS" VARCHAR2(20 BYTE), 
	"MARQUE" VARCHAR2(20 BYTE), 
	"TYPEV" VARCHAR2(20 BYTE), 
	"TYPECARBURANT" VARCHAR2(20 BYTE), 
	"DATECIRCULATION" VARCHAR2(20 BYTE), 
	"ID_EMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AYMEN.CARTEFIDELITE
SET DEFINE OFF;
Insert into AYMEN.CARTEFIDELITE (NUMERO,POINTS,CHEQUE,DATE_EM,DATE_EX,REFER_CLIENTS) values (4444,444,333333,to_date('01-JAN-00','DD-MON-RR'),to_date('19-JAN-00','DD-MON-RR'),12355);
Insert into AYMEN.CARTEFIDELITE (NUMERO,POINTS,CHEQUE,DATE_EM,DATE_EX,REFER_CLIENTS) values (2222,444,333333,to_date('09-JAN-00','DD-MON-RR'),to_date('28-JAN-00','DD-MON-RR'),12355);
REM INSERTING into AYMEN.CLIENTS
SET DEFINE OFF;
Insert into AYMEN.CLIENTS (REF_C,EMAIL,TELEPHONE,NOM_C,ADRESSE,PAYS) values (12355,'@','88888888','HEDI','TUNIS2','TUNIS');
Insert into AYMEN.CLIENTS (REF_C,EMAIL,TELEPHONE,NOM_C,ADRESSE,PAYS) values (22222,'@test','23454446','Ayz','adresseadaa','dza');
REM INSERTING into AYMEN.COLIS
SET DEFINE OFF;
Insert into AYMEN.COLIS (HAUTEUR,LARGEUR,LONGEUR,CODE_BARE,POIDS) values (11.1,11.1,11.1,123,11.1);
REM INSERTING into AYMEN.COMMANDE
SET DEFINE OFF;
Insert into AYMEN.COMMANDE (NUMERO,DESCRIPTION,DATEDECOMMANDE,MODEDEPAIMENT,MONTANT,ID_EMP,REF_CLIENT) values (1,'TY',to_date('01-JAN-00','DD-MON-RR'),'cheque',23,123,12355);
Insert into AYMEN.COMMANDE (NUMERO,DESCRIPTION,DATEDECOMMANDE,MODEDEPAIMENT,MONTANT,ID_EMP,REF_CLIENT) values (2,'T',to_date('01-JAN-00','DD-MON-RR'),'cheque',123,123,12355);
Insert into AYMEN.COMMANDE (NUMERO,DESCRIPTION,DATEDECOMMANDE,MODEDEPAIMENT,MONTANT,ID_EMP,REF_CLIENT) values (3,'T',to_date('01-JAN-00','DD-MON-RR'),'cheque',2,123,12355);
Insert into AYMEN.COMMANDE (NUMERO,DESCRIPTION,DATEDECOMMANDE,MODEDEPAIMENT,MONTANT,ID_EMP,REF_CLIENT) values (4,'PPP',to_date('16-MAY-00','DD-MON-RR'),'especes',111.232,123,22222);
REM INSERTING into AYMEN.COMMANDE_COLIS
SET DEFINE OFF;
Insert into AYMEN.COMMANDE_COLIS (NUMERO_C,ETAT,CODE_COLIS) values (1,'en cours',123);
Insert into AYMEN.COMMANDE_COLIS (NUMERO_C,ETAT,CODE_COLIS) values (2,'en cours',123);
REM INSERTING into AYMEN.CONGE
SET DEFINE OFF;
Insert into AYMEN.CONGE (IDC,NOM,PRENOM,DEB,FIN,DUREE,ETAT,IDEMP) values (123,'Aymen','Mzoughi',to_date('01-JAN-00','DD-MON-RR'),to_date('26-JAN-00','DD-MON-RR'),2,'TEST',123);
Insert into AYMEN.CONGE (IDC,NOM,PRENOM,DEB,FIN,DUREE,ETAT,IDEMP) values (1234,'Aymen23','Mzoughi',to_date('01-JAN-00','DD-MON-RR'),to_date('26-JAN-00','DD-MON-RR'),2,'TEST',123);
Insert into AYMEN.CONGE (IDC,NOM,PRENOM,DEB,FIN,DUREE,ETAT,IDEMP) values (11111,'RET','G5',to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),0,'TEST',123);
REM INSERTING into AYMEN.EMPLOYE
SET DEFINE OFF;
Insert into AYMEN.EMPLOYE (IDEMP,NOM,PRENOM,DATEN,NUMTEL,ADR,MAIL) values (123,'Aymenn','Mzoughi',to_date('01-JAN-00','DD-MON-RR'),'93781904','tunis','@esprit');
Insert into AYMEN.EMPLOYE (IDEMP,NOM,PRENOM,DATEN,NUMTEL,ADR,MAIL) values (12341,'Aymen','Mzoughi',to_date('11-JAN-00','DD-MON-RR'),'93781909','tunis','@esprit');
REM INSERTING into AYMEN.ENTREPOTS
SET DEFINE OFF;
Insert into AYMEN.ENTREPOTS (REF,ADRESSE,REGION,NSALLES,NVEHICULES) values (123,'TU','TUI','2','2');
REM INSERTING into AYMEN.USERS
SET DEFINE OFF;
Insert into AYMEN.USERS (ID,USERNAME,PASSWORD,ROLE) values (2,'aymen@gmail.com','123','assistantEmploye');
Insert into AYMEN.USERS (ID,USERNAME,PASSWORD,ROLE) values (1,'amine@gmail.com','123','assistantClient');
Insert into AYMEN.USERS (ID,USERNAME,PASSWORD,ROLE) values (4,'meriem@gmail.com','123','assistantStock');
Insert into AYMEN.USERS (ID,USERNAME,PASSWORD,ROLE) values (3,'zeineb@gmail.com','123','assistantCommande');
Insert into AYMEN.USERS (ID,USERNAME,PASSWORD,ROLE) values (0,'admin@gmail.com','123','admin');
REM INSERTING into AYMEN.VEHICULE
SET DEFINE OFF;
Insert into AYMEN.VEHICULE (MATRICULE,NUMDECHASSIS,MARQUE,TYPEV,TYPECARBURANT,DATECIRCULATION,ID_EMP) values ('123Tunis123','222','Fiat','camion','gazole','01-JAN-00',123);
Insert into AYMEN.VEHICULE (MATRICULE,NUMDECHASSIS,MARQUE,TYPEV,TYPECARBURANT,DATECIRCULATION,ID_EMP) values ('890Tunis222','1234','Fiat','camion','gazole','01-JAN-00',123);
Insert into AYMEN.VEHICULE (MATRICULE,NUMDECHASSIS,MARQUE,TYPEV,TYPECARBURANT,DATECIRCULATION,ID_EMP) values ('123Tunis124','222','Fiat','tricycle','gazole','01-JAN-00',123);
Insert into AYMEN.VEHICULE (MATRICULE,NUMDECHASSIS,MARQUE,TYPEV,TYPECARBURANT,DATECIRCULATION,ID_EMP) values ('890Tunis2','1234','Fiat','moto','gazole','01-JAN-00',123);
--------------------------------------------------------
--  DDL for Index CARTEFIDELITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYMEN"."CARTEFIDELITE_PK" ON "AYMEN"."CARTEFIDELITE" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYMEN"."CLIENTS_PK" ON "AYMEN"."CLIENTS" ("REF_C") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COLIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYMEN"."COLIS_PK" ON "AYMEN"."COLIS" ("CODE_BARE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYMEN"."COMMANDE_PK" ON "AYMEN"."COMMANDE" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYMEN"."CONGE_PK" ON "AYMEN"."CONGE" ("IDC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYMEN"."EMPLOYE_PK" ON "AYMEN"."EMPLOYE" ("IDEMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENTREPOTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYMEN"."ENTREPOTS_PK" ON "AYMEN"."ENTREPOTS" ("REF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYMEN"."ADMIN_PK" ON "AYMEN"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICULES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYMEN"."VEHICULES_PK" ON "AYMEN"."VEHICULE" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CARTEFIDELITE
--------------------------------------------------------

  ALTER TABLE "AYMEN"."CARTEFIDELITE" ADD CONSTRAINT "CARTEFIDELITE_PK" PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYMEN"."CARTEFIDELITE" MODIFY ("DATE_EX" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CARTEFIDELITE" MODIFY ("DATE_EM" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CARTEFIDELITE" MODIFY ("CHEQUE" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CARTEFIDELITE" MODIFY ("POINTS" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CARTEFIDELITE" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "AYMEN"."CLIENTS" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("REF_C")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYMEN"."CLIENTS" MODIFY ("REF_C" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CLIENTS" MODIFY ("PAYS" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CLIENTS" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CLIENTS" MODIFY ("NOM_C" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CLIENTS" MODIFY ("TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CLIENTS" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COLIS
--------------------------------------------------------

  ALTER TABLE "AYMEN"."COLIS" ADD CONSTRAINT "COLIS_PK" PRIMARY KEY ("CODE_BARE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYMEN"."COLIS" MODIFY ("CODE_BARE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "AYMEN"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYMEN"."COMMANDE" MODIFY ("MONTANT" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."COMMANDE" MODIFY ("MODEDEPAIMENT" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."COMMANDE" MODIFY ("DATEDECOMMANDE" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."COMMANDE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."COMMANDE" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE_COLIS
--------------------------------------------------------

  ALTER TABLE "AYMEN"."COMMANDE_COLIS" MODIFY ("NUMERO_C" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "AYMEN"."CONGE" ADD CONSTRAINT "CONGE_PK" PRIMARY KEY ("IDC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYMEN"."CONGE" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CONGE" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CONGE" MODIFY ("DUREE" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CONGE" MODIFY ("FIN" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CONGE" MODIFY ("DEB" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CONGE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CONGE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."CONGE" MODIFY ("IDC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "AYMEN"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("IDEMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYMEN"."EMPLOYE" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."EMPLOYE" MODIFY ("ADR" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."EMPLOYE" MODIFY ("NUMTEL" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."EMPLOYE" MODIFY ("DATEN" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."EMPLOYE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."EMPLOYE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."EMPLOYE" MODIFY ("IDEMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENTREPOTS
--------------------------------------------------------

  ALTER TABLE "AYMEN"."ENTREPOTS" ADD CONSTRAINT "ENTREPOTS_PK" PRIMARY KEY ("REF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYMEN"."ENTREPOTS" MODIFY ("NVEHICULES" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."ENTREPOTS" MODIFY ("NSALLES" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."ENTREPOTS" MODIFY ("REGION" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."ENTREPOTS" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."ENTREPOTS" MODIFY ("REF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "AYMEN"."USERS" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYMEN"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICULE
--------------------------------------------------------

  ALTER TABLE "AYMEN"."VEHICULE" ADD CONSTRAINT "VEHICULES_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYMEN"."VEHICULE" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CARTEFIDELITE
--------------------------------------------------------

  ALTER TABLE "AYMEN"."CARTEFIDELITE" ADD CONSTRAINT "FK_CLIENTS" FOREIGN KEY ("REFER_CLIENTS")
	  REFERENCES "AYMEN"."CLIENTS" ("REF_C") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "AYMEN"."COMMANDE" ADD CONSTRAINT "FK_IDEMP" FOREIGN KEY ("ID_EMP")
	  REFERENCES "AYMEN"."EMPLOYE" ("IDEMP") ENABLE;
  ALTER TABLE "AYMEN"."COMMANDE" ADD CONSTRAINT "FK_REFC" FOREIGN KEY ("REF_CLIENT")
	  REFERENCES "AYMEN"."CLIENTS" ("REF_C") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE_COLIS
--------------------------------------------------------

  ALTER TABLE "AYMEN"."COMMANDE_COLIS" ADD CONSTRAINT "FK_CODECOLIS" FOREIGN KEY ("CODE_COLIS")
	  REFERENCES "AYMEN"."COLIS" ("CODE_BARE") ENABLE;
  ALTER TABLE "AYMEN"."COMMANDE_COLIS" ADD CONSTRAINT "FK_NUMCM" FOREIGN KEY ("NUMERO_C")
	  REFERENCES "AYMEN"."COMMANDE" ("NUMERO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "AYMEN"."CONGE" ADD CONSTRAINT "FK_IDEMPC" FOREIGN KEY ("IDEMP")
	  REFERENCES "AYMEN"."EMPLOYE" ("IDEMP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEHICULE
--------------------------------------------------------

  ALTER TABLE "AYMEN"."VEHICULE" ADD CONSTRAINT "FK_IDE" FOREIGN KEY ("ID_EMP")
	  REFERENCES "AYMEN"."EMPLOYE" ("IDEMP") ENABLE;
